/* This file was autogenerated at 21:26:55 - do not edit it - any edits will be overwritten! */
package frc.robot;

import frc.utils.configfile.StormProp;

public final class Constants {
	public static final String debugProperties = StormProp.getString("general", "debugProperties", "");
	public static final String override = StormProp.getString("general", "override", "");
	public static final String robotName = StormProp.getString("general", "robotName", "");
	public static final String simOverride = StormProp.getString("general", "simOverride", "");
	public static final String simOverrideOverride = StormProp.getString("general", "simOverrideOverride", "");

	public static final class Akit {
		public static final Boolean doReplay = StormProp.getBoolean("akit", "doReplay", false);
	}

	public static final class ButtonBoard {
		public static final String driveJoystick = StormProp.getString("buttonBoard", "driveJoystick", "");
		public static final int driveJoystickPort = StormProp.getInt("buttonBoard", "driveJoystickPort", 0);
		public static final int drivePort = StormProp.getInt("buttonBoard", "drivePort", 0);
		public static final Boolean squarePath = StormProp.getBoolean("buttonBoard", "squarePath", false);
		public static final double stickNullSize = StormProp.getNumber("buttonBoard", "stickNullSize", 0.0);
	}

	public static final class Debug {
		public static final Boolean debug = StormProp.getBoolean("debug", "debug", false);
		public static final Boolean holdCrash = StormProp.getBoolean("debug", "holdCrash", false);
	}

	public static final class Drive {
		public static final Boolean allowRotation = StormProp.getBoolean("drive", "allowRotation", false);
		public static final Boolean angleOptimize = StormProp.getBoolean("drive", "angleOptimize", false);
		public static final double backLeftDiameter = StormProp.getNumber("drive", "backLeftDiameter", 0.0);
		public static final int backLeftDriveID = StormProp.getInt("drive", "backLeftDriveID", 0);
		public static final int backLeftEncoderID = StormProp.getInt("drive", "backLeftEncoderID", 0);
		public static final double backLeftEncoderOffset = StormProp.getNumber("drive", "backLeftEncoderOffset", 0.0);
		public static final int backLeftSteerID = StormProp.getInt("drive", "backLeftSteerID", 0);
		public static final double backRightDiameter = StormProp.getNumber("drive", "backRightDiameter", 0.0);
		public static final int backRightDriveID = StormProp.getInt("drive", "backRightDriveID", 0);
		public static final int backRightEncoderID = StormProp.getInt("drive", "backRightEncoderID", 0);
		public static final double backRightEncoderOffset = StormProp.getNumber("drive", "backRightEncoderOffset", 0.0);
		public static final int backRightSteerID = StormProp.getInt("drive", "backRightSteerID", 0);
		public static final Boolean cosineOptimize = StormProp.getBoolean("drive", "cosineOptimize", false);
		public static final Boolean driveCoastMode = StormProp.getBoolean("drive", "driveCoastMode", false);
		public static final double driveKD = StormProp.getNumber("drive", "driveKD", 0.0);
		public static final double driveKI = StormProp.getNumber("drive", "driveKI", 0.0);
		public static final double driveKMax = StormProp.getNumber("drive", "driveKMax", 0.0);
		public static final double driveKMin = StormProp.getNumber("drive", "driveKMin", 0.0);
		public static final double driveKP = StormProp.getNumber("drive", "driveKP", 0.0);
		public static final double driveOpenLoopRampRate = StormProp.getNumber("drive", "driveOpenLoopRampRate", 0.0);
		public static final double driveRatio = StormProp.getNumber("drive", "driveRatio", 0.0);
		public static final double driveSpeedScale = StormProp.getNumber("drive", "driveSpeedScale", 0.0);
		public static final String driveSubtype = StormProp.getString("drive", "driveSubtype", "");
		public static final String driveType = StormProp.getString("drive", "driveType", "");
		public static final double drivetrainTrackwidthMeters = StormProp.getNumber("drive", "drivetrainTrackwidthMeters", 0.0);
		public static final double drivetrainWheelbaseMeters = StormProp.getNumber("drive", "drivetrainWheelbaseMeters", 0.0);
		public static final double frontLeftDiameter = StormProp.getNumber("drive", "frontLeftDiameter", 0.0);
		public static final int frontLeftDriveID = StormProp.getInt("drive", "frontLeftDriveID", 0);
		public static final int frontLeftEncoderID = StormProp.getInt("drive", "frontLeftEncoderID", 0);
		public static final double frontLeftEncoderOffset = StormProp.getNumber("drive", "frontLeftEncoderOffset", 0.0);
		public static final int frontLeftSteerID = StormProp.getInt("drive", "frontLeftSteerID", 0);
		public static final double frontRightDiameter = StormProp.getNumber("drive", "frontRightDiameter", 0.0);
		public static final int frontRightDriveID = StormProp.getInt("drive", "frontRightDriveID", 0);
		public static final int frontRightEncoderID = StormProp.getInt("drive", "frontRightEncoderID", 0);
		public static final double frontRightEncoderOffset = StormProp.getNumber("drive", "frontRightEncoderOffset", 0.0);
		public static final int frontRightSteerID = StormProp.getInt("drive", "frontRightSteerID", 0);
		public static final Boolean invertEncoder = StormProp.getBoolean("drive", "invertEncoder", false);
		public static final Boolean invertRight = StormProp.getBoolean("drive", "invertRight", false);
		public static final Boolean invertSteer = StormProp.getBoolean("drive", "invertSteer", false);
		public static final double linearRateLimiter = StormProp.getNumber("drive", "linearRateLimiter", 0.0);
		public static final double maxMotorVoltage = StormProp.getNumber("drive", "maxMotorVoltage", 0.0);
		public static final Boolean resetOrientation = StormProp.getBoolean("drive", "resetOrientation", false);
		public static final Boolean steerCoastMode = StormProp.getBoolean("drive", "steerCoastMode", false);
		public static final double steerKD = StormProp.getNumber("drive", "steerKD", 0.0);
		public static final double steerKI = StormProp.getNumber("drive", "steerKI", 0.0);
		public static final double steerKMax = StormProp.getNumber("drive", "steerKMax", 0.0);
		public static final double steerKMin = StormProp.getNumber("drive", "steerKMin", 0.0);
		public static final double steerKP = StormProp.getNumber("drive", "steerKP", 0.0);
		public static final double steerOpenLoopRampRate = StormProp.getNumber("drive", "steerOpenLoopRampRate", 0.0);
		public static final double steerRatio = StormProp.getNumber("drive", "steerRatio", 0.0);
		public static final double turnRateLimiter = StormProp.getNumber("drive", "turnRateLimiter", 0.0);
		public static final Boolean useFieldRelative = StormProp.getBoolean("drive", "useFieldRelative", false);
	}

	public static final class Frame {
		public static final double length = StormProp.getNumber("frame", "length", 0.0);
		public static final double width = StormProp.getNumber("frame", "width", 0.0);
	}

	public static final class Lights {
		public static final double batteryPulsePeriod = StormProp.getNumber("lights", "batteryPulsePeriod", 0.0);
		public static final int ledLength = StormProp.getInt("lights", "ledLength", 0);
		public static final int leftViewEnd = StormProp.getInt("lights", "leftViewEnd", 0);
		public static final int leftViewStart = StormProp.getInt("lights", "leftViewStart", 0);
		public static final int port = StormProp.getInt("lights", "port", 0);
		public static final int rightViewEnd = StormProp.getInt("lights", "rightViewEnd", 0);
		public static final int rightViewStart = StormProp.getInt("lights", "rightViewStart", 0);
	}

	public static final class Power {
		public static final Boolean autoKill = StormProp.getBoolean("power", "autoKill", false);
		public static final Boolean isRevPdh = StormProp.getBoolean("power", "isRevPdh", false);
		public static final int moduleID = StormProp.getInt("power", "moduleID", 0);
		public static final double shutoffLimit = StormProp.getNumber("power", "shutoffLimit", 0.0);
		public static final double warnLimit = StormProp.getNumber("power", "warnLimit", 0.0);
	}

	public static final class Shooter {
		public static final double intakeMaxSpeed = StormProp.getNumber("shooter", "intakeMaxSpeed", 0.0);
		public static final Boolean invertIntake = StormProp.getBoolean("shooter", "invertIntake", false);
		public static final Boolean invertLeader = StormProp.getBoolean("shooter", "invertLeader", false);
		public static final double lowerDiameter = StormProp.getNumber("shooter", "lowerDiameter", 0.0);
		public static final double lowerGearRatio = StormProp.getNumber("shooter", "lowerGearRatio", 0.0);
		public static final int lowerID = StormProp.getInt("shooter", "lowerID", 0);
		public static final double openLoopRampRate = StormProp.getNumber("shooter", "openLoopRampRate", 0.0);
		public static final double outtakeMaxSpeed = StormProp.getNumber("shooter", "outtakeMaxSpeed", 0.0);
		public static final double outtakeTimerSec = StormProp.getNumber("shooter", "outtakeTimerSec", 0.0);
		public static final double shootMaxSpeed = StormProp.getNumber("shooter", "shootMaxSpeed", 0.0);
		public static final double shootTimerSec = StormProp.getNumber("shooter", "shootTimerSec", 0.0);
		public static final double upperDiameter = StormProp.getNumber("shooter", "upperDiameter", 0.0);
		public static final int upperFollowerID = StormProp.getInt("shooter", "upperFollowerID", 0);
		public static final double upperGearRatio = StormProp.getNumber("shooter", "upperGearRatio", 0.0);
		public static final int upperLeaderID = StormProp.getInt("shooter", "upperLeaderID", 0);
		public static final Boolean useSlider = StormProp.getBoolean("shooter", "useSlider", false);
	}

	public static final class SparkConstants {
		public static final int CurrentLimit = StormProp.getInt("sparkConstants", "CurrentLimit", 0);
		public static final int FreeSpeedRPM = StormProp.getInt("sparkConstants", "FreeSpeedRPM", 0);
		public static final int Neo550CurrentLimit = StormProp.getInt("sparkConstants", "Neo550CurrentLimit", 0);
		public static final int Neo550FreeSpeedRPM = StormProp.getInt("sparkConstants", "Neo550FreeSpeedRPM", 0);
		public static final double Neo550NominalVoltage = StormProp.getNumber("sparkConstants", "Neo550NominalVoltage", 0.0);
		public static final double NominalVoltage = StormProp.getNumber("sparkConstants", "NominalVoltage", 0.0);
	}

	public static final class TalonConstants {
		public static final double driveStatorCurrentLimit = StormProp.getNumber("talonConstants", "driveStatorCurrentLimit", 0.0);
		public static final double steerStatorCurrentLimit = StormProp.getNumber("talonConstants", "steerStatorCurrentLimit", 0.0);
	}

	public static final class Toggles {
		public static final Boolean useAdvantageKit = StormProp.getBoolean("toggles", "useAdvantageKit", false);
		public static final Boolean useBatteryMonitor = StormProp.getBoolean("toggles", "useBatteryMonitor", false);
		public static final Boolean useDrive = StormProp.getBoolean("toggles", "useDrive", false);
		public static final Boolean useLights = StormProp.getBoolean("toggles", "useLights", false);
		public static final Boolean usePidTuner = StormProp.getBoolean("toggles", "usePidTuner", false);
		public static final Boolean useShooter = StormProp.getBoolean("toggles", "useShooter", false);
		public static final Boolean useWebServer = StormProp.getBoolean("toggles", "useWebServer", false);
	}
}

