/* This file was autogenerated at {21:26:55} - do not edit it - any edits will be overwritten! */
package frc.robot;

import frc.utils.configfile.OptionsController;
import frc.utils.configfile.Option;
import frc.utils.configfile.OptionsRegistry;

public final class Options {
    public static void periodic() {
        OptionsRegistry.periodic();
    }

    public static class DriveOptions extends OptionsController {

        public final Option<Boolean> useFieldRelative;
        public final Option<Boolean> allowRotation;
        public final Option<Boolean> resetOrientation;

        private static DriveOptions instance;

        public DriveOptions() {
            super("Drive Options");
            useFieldRelative = createBooleanOption("useFieldRelative", Constants.Drive.useFieldRelative);
            allowRotation = createBooleanOption("allowRotation", Constants.Drive.allowRotation);
            resetOrientation = createBooleanOption("resetOrientation", Constants.Drive.resetOrientation);
            OptionsRegistry.register(this);
        }

        public static DriveOptions create() {
            if (instance == null) {
                instance = new DriveOptions();
            }
            return instance;
        }
    }
}
