/* This file was autogenerated at {01:16:42} - do not edit it - any edits will be overwritten! */
package frc.robot;

import frc.utils.configfile.OptionsController;
import frc.utils.configfile.Option;
import frc.utils.configfile.OptionsRegistry;

public final class Options {

    public static class DriveOptions extends OptionsController {

        public final Option<Boolean> cosineOptimize;
        public final Option<Boolean> allowRotation;
        public final Option<Boolean> angleOptimize;
        private static DriveOptions instance;

        public DriveOptions() {
            super("Drive Options");
            cosineOptimize = createBooleanOption("cosineOptimize", Constants.Drive.cosineOptimize);
            allowRotation = createBooleanOption("allowRotation", Constants.Drive.allowRotation);
            angleOptimize = createBooleanOption("angleOptimize", Constants.Drive.angleOptimize);
            OptionsRegistry.register(this);
        }

        public static DriveOptions create() {
            if (instance == null) {
                instance = new DriveOptions();
            }
            return instance;
        }
    }

    public static void periodic() {
        OptionsRegistry.periodic();
    }
}
