/* This file was autogenerated at {23:03:30} - do not edit it - any edits will be overwritten! */
package frc.robot.elastic.options;

import frc.robot.Constants;
import frc.robot.elastic.OptionsController;
import frc.robot.elastic.Option;
public class DriveOptions extends OptionsController {

    public final Option<Boolean> cosineOptimize;
    public final Option<Boolean> allowRotation;
    public final Option<Boolean> angleOptimize;

    public DriveOptions() {
        super("Drive Options");
        cosineOptimize = createBooleanOption("cosineOptimize", Constants.Drive.cosineOptimize);
        allowRotation = createBooleanOption("allowRotation", Constants.Drive.allowRotation);
        angleOptimize = createBooleanOption("angleOptimize", Constants.Drive.angleOptimize);
    }
}
