package frc.utils.generator;

import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import static java.lang.System.exit;

public class ConstantGenerator {

    static Map<String, Map<String, PropItem>> allConstants = new HashMap<>();
    static Map<String, String> properties = new HashMap<>();
    public static StringBuilder program = new StringBuilder();
    public static final String PROGRAM_HEADER = String.format("""
            /* This file was autogenerated at %s - do not edit it - any edits will be overwritten! */ 
            package frc.robot;

            import frc.utils.configfile.StormProp;
            """,
            java.time.LocalTime.now().format(java.time.format.DateTimeFormatter.ofPattern("HH:mm:ss")));

    private static String indent(String s, int n) {
        return "\t".repeat(Math.max(0, n)) + s + "\n";
    }

    public static void programWriter() {
        int tabs = 0;
        program.append(PROGRAM_HEADER);
        program.append("\npublic final class Constants {\n");
        tabs += 1;
        List<String> prefixes = new ArrayList<>(allConstants.keySet());
        prefixes.sort(null);
        prefixes.remove("general");
        prefixes.add(0, "general");

        for (String prefix : prefixes) {
            if (!prefix.equals("general")) {
                program.append("\n");
                program.append(indent("public static final class "
                        + prefix.substring(0, 1).toUpperCase()
                        + prefix.substring(1)
                        + " {", tabs));
                tabs += 1;
                List<String> sortedKeys = new ArrayList<>(allConstants.get(prefix).keySet());
                sortedKeys.sort(null);

                for (String key : sortedKeys) {
                    program.append(indent(allConstants.get(prefix).get(key).toString(), tabs));
                }
                tabs -= 1;
                program.append(indent("}", tabs));
            } else {
                List<String> sortedKeys = new ArrayList<>(allConstants.get(prefix).keySet());
                sortedKeys.sort(null);
                for (String k : sortedKeys) {
                    program.append(indent(allConstants.get(prefix).get(k).toString(), tabs));
                }
            }
        }
        tabs -= 1;
        program.append(indent("}\n", tabs));
    }

    public static void init(String path) throws IOException {
        try (FileReader reader = new FileReader(path + "/config.properties")) {
            Properties p = new Properties();
            p.load(reader);
            List<String> propFiles = new ArrayList<>();

            Enumeration<Object> keys = p.keys();
            while (keys.hasMoreElements()) {
                Object key = keys.nextElement();
                if (key.toString().contains("robot.")) {
                    propFiles.add(p.get(key).toString());
                } else {
                    properties.put(key.toString(), p.get(key).toString());
                }
            }

            // Load property files
            for (String propFile : propFiles) {
                try (FileReader propReader = new FileReader(path + "/" + propFile)) {
                    p = new Properties();
                    p.load(propReader);
                    keys = p.keys();
                    while (keys.hasMoreElements()) {
                        Object key = keys.nextElement();
                        properties.put(key.toString(), p.get(key).toString());
                    }
                } catch (IOException e) {
                    System.err.println("Error reading property file " + propFile + ": " + e.getMessage());
                }
            }

            // Process properties
            for (Map.Entry<String, String> entry : properties.entrySet()) {
                try {
                    String typeAndTags = "";
                    if (entry.getValue().contains("(")) {
                        typeAndTags = entry.getValue().substring(
                                entry.getValue().indexOf("(") + 1,
                                entry.getValue().indexOf(")"));
                    }

                    String prefix = entry.getKey().contains(".")
                            ? entry.getKey().substring(0, entry.getKey().indexOf("."))
                            : "general";

                    String baseType = typeAndTags.split(",")[0].trim().toLowerCase();
                    Object defaultVal = switch (baseType) {
                        case "int" ->
                            0;
                        case "number" ->
                            0.0;
                        case "boolean" ->
                            false;
                        default ->
                            "";
                    };

                    String itemKey = entry.getKey().replace(prefix + ".", "");
                    PropItem newItem = new PropItem(typeAndTags, itemKey,
                            defaultVal.toString(), prefix);

                    if (allConstants.containsKey(prefix)) {
                        if (allConstants.get(prefix).containsKey(itemKey)) {
                            if (!allConstants.get(prefix).get(itemKey).equals(newItem)) {
                                throw new IllegalStateException(
                                        "Build Failed: Error in Generating Constants - mismatched types!");
                            }
                        } else {
                            allConstants.get(prefix).put(itemKey, newItem);
                        }
                    } else {
                        Map<String, PropItem> prefixMap = new HashMap<>();
                        prefixMap.put(itemKey, newItem);
                        allConstants.put(prefix, prefixMap);
                    }
                } catch (IllegalArgumentException | IllegalStateException e) {
                    System.err.println("Error processing property " + entry.getKey() + ": " + e.getMessage());
                }
            }
        }
    }

    public static void main(String[] args) {
        if (args.length != 2) {
            System.err.println("usage: program INPUTFILEDIR OUTPUTFILENAME");
            exit(1);
        }

        String inputFileDir = args[0];
        String outputFileName = args[1];
        String optionsDir = outputFileName.substring(0, outputFileName.lastIndexOf("/"));

        try {
            init(inputFileDir);
            programWriter();

            // Generate Constants.java
            try (FileWriter output = new FileWriter(outputFileName)) {
                output.write(program.toString());
                System.out.println("Constants file generated successfully.");
            }

            // Generate Options class
            OptionsGenerator.generateOptions(allConstants, optionsDir);

        } catch (IOException e) {
            System.err.println("Error during code generation: " + e.getMessage());
            exit(1);
        }
    }
}
