package frc.utils.generator;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

public class OptionsGenerator {

    private static final String CLASS_HEADER = """
        /* This file was autogenerated at {%s} - do not edit it - any edits will be overwritten! */
        package frc.robot;

        import frc.utils.configfile.OptionsController;
        import frc.utils.configfile.Option;
        import frc.utils.configfile.OptionsRegistry;

        public final class Options {
            public static void periodic() {
                OptionsRegistry.periodic();
            }
        """;

    private static String generateOptionsClass(String prefix, Map<String, PropItem> props) {
        StringBuilder sb = new StringBuilder();

        // Begin class definition
        String className = prefix.substring(0, 1).toUpperCase() + prefix.substring(1) + "Options";
        sb.append(String.format("    public static class %s extends OptionsController {\n\n", className));

        // Declare option fields
        for (PropItem prop : props.values()) {
            if (prop.isOption()) {
                String name = prop.getKey();
                sb.append(String.format("        public final Option<%s> %s;\n",
                        prop.getPropertyType().getJavaType(), name));
            }
        }

        // Add static instance field
        sb.append("\n        private static " + className + " instance;\n\n");

        // Constructor
        sb.append(String.format("        public %s() {\n", className));
        sb.append(String.format("            super(\"%s Options\");\n",
                prefix.substring(0, 1).toUpperCase() + prefix.substring(1)));

        // Initialize options
        for (PropItem prop : props.values()) {
            if (prop.isOption()) {
                String name = prop.getKey();
                String constRef = String.format("Constants.%s.%s",
                        prefix.substring(0, 1).toUpperCase() + prefix.substring(1),
                        name);

                String createMethod = switch (prop.getPropertyType()) {
                    case BOOLEAN ->
                        "createBooleanOption";
                    case NUMBER ->
                        "createNumberOption";
                    case INTEGER ->
                        "createIntegerOption";
                    case STRING ->
                        "createStringOption";
                };

                sb.append(String.format("            %s = %s(\"%s\", %s);\n",
                        name, createMethod, name, constRef));
            }
        }

        // Register with OptionsRegistry
        sb.append("            OptionsRegistry.register(this);\n");
        sb.append("        }\n\n");

        // Add create() method
        sb.append("        public static " + className + " create() {\n");
        sb.append("            if (instance == null) {\n");
        sb.append("                instance = new " + className + "();\n");
        sb.append("            }\n");
        sb.append("            return instance;\n");
        sb.append("        }\n");

        sb.append("    }\n");

        return sb.toString();
    }

    public static void generateOptions(Map<String, Map<String, PropItem>> constants, String outputDir) {
        // Create output directory if it doesn't exist
        File outDir = new File(outputDir);
        if (!outDir.exists() && !outDir.mkdirs()) {
            System.err.println("Failed to create output directory: " + outputDir);
            return;
        }

        StringBuilder optionsFile = new StringBuilder();
        optionsFile.append(String.format(CLASS_HEADER,
                java.time.LocalTime.now().format(java.time.format.DateTimeFormatter.ofPattern("HH:mm:ss"))));

        // Group properties by prefix and filter for those with options
        for (Map.Entry<String, Map<String, PropItem>> entry : constants.entrySet()) {
            String prefix = entry.getKey();
            Map<String, PropItem> props = entry.getValue();

            // Check if any properties in this prefix are marked as options
            boolean hasOptions = props.values().stream().anyMatch(PropItem::isOption);
            if (hasOptions) {
                optionsFile.append("\n");
                optionsFile.append(generateOptionsClass(prefix, props));
            }
        }

        optionsFile.append("}\n");

        String fileName = outputDir + "/Options.java";
        try (FileWriter writer = new FileWriter(fileName)) {
            writer.write(optionsFile.toString());
            System.out.println("Generated Options class");
        } catch (IOException e) {
            System.err.println("Error generating Options class: " + e.getMessage());
        }
    }
}
