package frc.utils.generator;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

public class OptionsGenerator {

    private static final String HEADER_TEMPLATE = """
        /* This file was autogenerated at {%s} - do not edit it - any edits will be overwritten! */
        package frc.robot.elastic.options;

        import frc.robot.Constants;
        import frc.robot.elastic.OptionsController;
        import frc.robot.elastic.Option;
        """;

    private static String generateOptionsClass(String prefix, Map<String, PropItem> props) {
        StringBuilder sb = new StringBuilder();

        // Add header with timestamp
        sb.append(String.format(HEADER_TEMPLATE,
                java.time.LocalTime.now().format(java.time.format.DateTimeFormatter.ofPattern("HH:mm:ss"))));

        // Begin class definition
        String className = prefix.substring(0, 1).toUpperCase() + prefix.substring(1) + "Options";
        sb.append(String.format("public class %s extends OptionsController {\n\n", className));

        // Declare option fields
        for (PropItem prop : props.values()) {
            if (prop.isOption()) {
                String name = prop.getKey();
                sb.append(String.format("    public final Option<%s> %s;\n",
                        prop.getPropertyType().getJavaType(), name));
            }
        }
        sb.append("\n");

        // Constructor
        sb.append(String.format("    public %s() {\n", className));
        sb.append(String.format("        super(\"%s Options\");\n",
                prefix.substring(0, 1).toUpperCase() + prefix.substring(1)));

        // Initialize options
        for (PropItem prop : props.values()) {
            if (prop.isOption()) {
                String name = prop.getKey();
                String constRef = String.format("Constants.%s.%s",
                        prefix.substring(0, 1).toUpperCase() + prefix.substring(1),
                        name);

                String createMethod = switch (prop.getPropertyType()) {
                    case BOOLEAN ->
                        "createBooleanOption";
                    case NUMBER ->
                        "createNumberOption";
                    case INTEGER ->
                        "createIntegerOption";
                    case STRING ->
                        "createStringOption";
                };

                sb.append(String.format("        %s = %s(\"%s\", %s);\n",
                        name, createMethod, name, constRef));
            }
        }

        sb.append("    }\n");
        sb.append("}\n");

        return sb.toString();
    }

    public static void generateOptions(Map<String, Map<String, PropItem>> constants, String outputDir) {
        // Create output directory if it doesn't exist
        File outDir = new File(outputDir);
        if (!outDir.exists() && !outDir.mkdirs()) {
            System.err.println("Failed to create output directory: " + outputDir);
            return;
        }

        // Group properties by prefix and filter for those with options
        for (Map.Entry<String, Map<String, PropItem>> entry : constants.entrySet()) {
            String prefix = entry.getKey();
            Map<String, PropItem> props = entry.getValue();

            // Check if any properties in this prefix are marked as options
            boolean hasOptions = props.values().stream().anyMatch(PropItem::isOption);
            if (hasOptions) {
                String fileName = outputDir + "/"
                        + prefix.substring(0, 1).toUpperCase()
                        + prefix.substring(1) + "Options.java";

                try (FileWriter writer = new FileWriter(fileName)) {
                    writer.write(generateOptionsClass(prefix, props));
                    System.out.println("Generated options class for prefix: " + prefix);
                } catch (IOException e) {
                    System.err.println("Error generating options for prefix " + prefix + ": " + e.getMessage());
                }
            }
        }
    }
}
